### PR TITLE
fix(support springboot1): override method to avoid no default method

### PR DESCRIPTION
**Pull request by qixiaobo**
override method to avoid no default method support in interface

### Motivation
override method to avoid no default method support in interface

override method to avoid no default method support in interface In previous spring framework , BeanPostProcessor not use default method in interface. We should override this method to avoid cause AbstractMethodError in this case.

### Modification

Just add override method

### Result

Resolved or fixed #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Review by lvjing2 — APPROVED** [review]
LGTM

**Comment by lvjing2** [comment]
这两个报错，一个是 cla, 一个是需要本地先执行下格式化 mvn clean package 命令

**Review by TomorJM — APPROVED** [review]
LGTM

**Comment by glmapper** [comment]
LGTM

**Pull request merged**
